### ISSUE TITLE
Support for otf

### ISSUE THREAD

**Issue by aastefian** [papandreou/subset-font#3]
Hello,

I see in the package description that the library only supports ttf, woff, woff2. But i tried converting a .otf file and it worked, no errors were shown. I saw that fontverter, a dependency of yours uses woff2sfnt-sfnt2woff as dependency (https://www.npmjs.com/package/woff2sfnt-sfnt2woff) , which in turn supports otf conversion, I think thats why it still worked, if it is the case maybe that is something you can validate and test and then you could add it to the package description, this would be a big added value i think, because as of now your package was the only one supporting conversion & subsetting of woff, woff2 and ttf in a nice package with a nice interface. Adding otf to that list would be awesome.

Cheers!

**Comment by papandreou** [comment]
Thanks for bringing this up! I have to read up on the differences between .otf and .ttf, but amazing that it just works :)

I guess it's because it's based on the same container format and directly supported by harfbuzz, and `fontverter` will just pretend it's a truetype font because of https://github.com/papandreou/fontverter/blob/2332d27efac388598fdf6afe7929e2b3bc296249/index.js#L14

**Comment by papandreou** [comment]
Seems most reasonable to just call it `sfnt` instead of `truetype`. Fixed in bb581a20f44617f2fa32a73c92a6f3aba438b4e4 / 1.2.0. Also made the change in fontverter 2.0.0 (https://github.com/papandreou/fontverter/commit/4b5473931b8b715c83767f75c93a9f76aef63dcb)
